address issues

diff --git a/.github/workflows/coverage.yaml b/.github/workflows/coverage.yaml
--- a/.github/workflows/coverage.yaml
+++ b/.github/workflows/coverage.yaml
@@ -4,7 +4,8 @@ on:
   pull_request:
     paths:
       - 'tests/**' # This triggers the workflow for any changes in the tests folder
-      - '!tests/prague/**'  # This excludes changes in 'tests/prague'
+      - '!tests/prague/**'  # exclude changes in 'tests/prague'
+      - '!tests/osaka/**'   # exclude changes in 'tests/osaka'
 
 jobs:
   evmone-coverage-diff:
@@ -32,6 +33,7 @@ jobs:
             tests:
               - tests/**/test_*.py
               - '!tests/prague/**'
+              - '!tests/osaka/**'
             converted_tests:
               - converted-ethereum-tests.txt
 
@@ -173,8 +175,7 @@ jobs:
           mkdir -p fixtures/state_tests
           mkdir -p fixtures/eof_tests
 
-          uv run fill $files --until=Cancun --evm-bin evmone-t8n || true >> filloutput.log 2>&1
-          (uv run fill $files --fork=PragueEIP7692 --evm-bin evmone-t8n || true) > >(tee -a filloutput.log filloutputEOF.log) 2>&1
+          uv run fill $files -n auto --until=Cancun --evm-bin evmone-t8n || true >> filloutput.log 2>&1
 
           if grep -q "FAILURES" filloutput.log; then
               echo "Error: failed to generate .py tests."
@@ -224,36 +225,35 @@ jobs:
 
             rm -r fixtures
             rm filloutput.log
-            rm filloutputEOF.log
             mkdir -p fixtures/state_tests
             mkdir -p fixtures/eof_tests
 
-            uv run fill $files_fixed --until=Cancun --evm-bin evmone-t8n || true >> filloutput.log 2>&1
-            (uv run fill $files_fixed --fork=PragueEIP7692 --evm-bin evmone-t8n || true) > >(tee -a filloutput.log filloutputEOF.log) 2>&1
+            if [ -n "$files_fixed" ]; then
+                uv run fill $files_fixed -n auto --until=Cancun --evm-bin evmone-t8n || true >> filloutput.log 2>&1
 
-            if grep -q "FAILURES" filloutput.log; then
-              echo "Error: failed to generate .py tests from before the PR."
-              exit 1
-            fi
-
-            if grep -q "ERROR collecting test session" filloutput.log; then
-              echo "Error: failed to generate .py tests from before the PR."
-              exit 1
-            fi
-
-            filesState=$(find fixtures/state_tests -type f -name "*.json")
-            filesEOF=$(find fixtures/eof_tests -type f -name "*.json")
-
-            BASE_TEST_PATH=${{ github.workspace }}/evmtest_coverage/coverage/BASE_TESTS
-            mkdir -p $BASE_TEST_PATH
-            find fixtures/state_tests -type f -name "*.json" -exec cp {} $BASE_TEST_PATH \;
-            find fixtures/eof_tests -type f -name "*.json" -exec cp {} $BASE_TEST_PATH \;
-            for file in $BASE_TEST_PATH/*.json; do
-                if [ -e "$file" ]; then
-                    mv "$file" "${file%.json}_$PREV_COMMIT.json"
+                if grep -q "FAILURES" filloutput.log; then
+                  echo "Error: failed to generate .py tests from before the PR."
+                  exit 1
                 fi
-            done
 
+                if grep -q "ERROR collecting test session" filloutput.log; then
+                  echo "Error: failed to generate .py tests from before the PR."
+                  exit 1
+                fi
+
+                filesState=$(find fixtures/state_tests -type f -name "*.json")
+                filesEOF=$(find fixtures/eof_tests -type f -name "*.json")
+
+                BASE_TEST_PATH=${{ github.workspace }}/evmtest_coverage/coverage/BASE_TESTS
+                mkdir -p $BASE_TEST_PATH
+                find fixtures/state_tests -type f -name "*.json" -exec cp {} $BASE_TEST_PATH \;
+                find fixtures/eof_tests -type f -name "*.json" -exec cp {} $BASE_TEST_PATH \;
+                for file in $BASE_TEST_PATH/*.json; do
+                    if [ -e "$file" ]; then
+                        mv "$file" "${file%.json}_$PREV_COMMIT.json"
+                    fi
+                done
+            fi
 
       - name: Print tests that will be covered
         if: ${{ steps.changed-tests.outputs.tests_any_changed == 'true' }}
