build the changed files array once

diff --git a/.github/workflows/coverage.yaml b/.github/workflows/coverage.yaml
--- a/.github/workflows/coverage.yaml
+++ b/.github/workflows/coverage.yaml
@@ -16,8 +16,38 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Fetch target branch
-        run: git fetch origin ${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
+      - name: Fetch github branches and detect introduces .py files
+        run: |
+          if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
+              # Fetch changes when PR comes from remote repo
+              git fetch origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
+              git fetch origin +refs/pull/${{ github.event.pull_request.number }}/head:refs/remotes/origin/PR-${{ github.event.pull_request.number }}
+              files=$(git diff --name-status origin/${{ github.base_ref }}...origin/PR-${{ github.event.pull_request.number }} -- tests/ | grep -E '^[AM]' | grep '\.py$')
+          else
+              # Fetch the base branch and the head branch
+              git fetch origin ${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
+              git fetch origin ${{ github.head_ref }}:refs/remotes/origin/${{ github.head_ref }}
+              files=$(git diff --name-status origin/${{ github.base_ref }}...origin/${{ github.head_ref }} -- tests/ | grep -E '^[AM]' | grep '\.py$')
+          fi
+
+          # Eliminate git diff chars, select only .py paths
+          echo "Collect the changed .py files"
+          py_files=()
+          while read -r line; do
+              file_fixed=$(echo "$line" | cut -c 3-)
+              py_files+=("$file_fixed")
+          done <<< "$files"
+
+          echo "Prepare the NEW_TESTS variable"
+          py_files_str=$(IFS=,; echo "${py_files[*]}")
+          echo "NEW_TESTS=$py_files_str" >> $GITHUB_ENV
+
+          echo "Detected new/changed .py files:"
+          source $GITHUB_ENV
+          files2=$(echo "$NEW_TESTS" | tr ',' '\n')
+          while IFS= read -r file; do
+            echo $file
+          done <<< "$files2"
 
       - name: Log in to Docker Hub
         uses: docker/login-action@v3
@@ -120,29 +150,11 @@ jobs:
       # This command diffs the .py scripts introduced by a PR
       - name: Parse and fill introduced test sources
         run: |
+          source $GITHUB_ENV
+          files=$(echo "$NEW_TESTS" | tr ',' '\n')
+
           python3 -m venv ./venv/
           source ./venv/bin/activate
-
-          if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
-              # Fetch changes when PR comes from remote repo
-              git fetch origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
-              git fetch origin +refs/pull/${{ github.event.pull_request.number }}/head:refs/remotes/origin/PR-${{ github.event.pull_request.number }}
-              files=$(git diff --name-status origin/${{ github.base_ref }}...origin/PR-${{ github.event.pull_request.number }} -- tests/ | grep -E '^[AM]' | grep '\.py$')
-          else
-              # Fetch the base branch and the head branch
-              git fetch origin ${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
-              git fetch origin ${{ github.head_ref }}:refs/remotes/origin/${{ github.head_ref }}
-
-              # Perform the diff
-              files=$(git diff --name-status origin/${{ github.base_ref }}...origin/${{ github.head_ref }} -- tests/ | grep -E '^[AM]' | grep '\.py$')
-          fi
-
-
-          echo "Modified or new .py files in tests folder:"
-          echo "$files" | while read line; do
-            file=$(echo "$line" | cut -c 3-)
-            echo $file
-          done
 
           # fill new tests
           # using `|| true` here because if no tests found, pyspec fill returns error code
@@ -150,8 +162,8 @@ jobs:
           mkdir -p fixtures/eof_tests
 
           # Use a while loop with a here-string to avoid subshell issues
-          while IFS= read -r line; do
-            file=$(echo "$line" | cut -c 3-)
+          while IFS= read -r file; do
+            echo "Fill: $file"
             fill "$file" --until=Cancun --evm-bin evmone-t8n || true >> filloutput.log 2>&1
             (fill "$file" --fork=CancunEIP7692 --evm-bin evmone-t8n -k eof_test || true) > >(tee -a filloutput.log filloutputEOF.log) 2>&1
           done <<< "$files"
@@ -170,6 +182,14 @@ jobs:
 
           filesState=$(find fixtures/state_tests -type f -name "*.json")
           filesEOF=$(find fixtures/eof_tests -type f -name "*.json")
+          if [ -z "$filesState" ] && [ -z "$filesEOF" ]; then
+              echo "Error: No filled JSON fixtures found in fixtures."
+               exit 1
+          fi
+
+          # Include basic evm operations into coverage by default
+          # As when we translate from yul/solidity some dup/push opcodes could become untouched
+          fill tests/homestead/coverage/test_coverage.py --until=Cancun --evm-bin evmone-t8n
 
           PATCH_TEST_PATH=${{ github.workspace }}/evmtest_coverage/coverage/PATCH_TESTS
           mkdir -p $PATCH_TEST_PATH
@@ -182,17 +202,9 @@ jobs:
             echo "--------------------"
             echo "converted-ethereum-tests.txt seem untouched, try to fill pre-patched version of .py files:"
 
-            if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
-               files=$(git diff --name-status origin/${{ github.base_ref }}...origin/PR-${{ github.event.pull_request.number }} -- tests/ | grep -E '^[AM]' | grep '\.py$')
-            else
-               files=$(git diff --name-status origin/${{ github.base_ref }}...origin/${{ github.head_ref }} -- tests/ | grep -E '^[AM]' | grep '\.py$')
-            fi
-
-            echo "Modified or new .py files in tests folder:"
-            echo "$files" | while read line; do
-              file=$(echo "$line" | cut -c 3-)
-              echo $file
-            done
+            # load introduces .py files
+            source $GITHUB_ENV
+            files=$(echo "$NEW_TESTS" | tr ',' '\n')
 
             git checkout main
             PREV_COMMIT=$(git rev-parse HEAD)
@@ -207,8 +219,9 @@ jobs:
             mkdir -p fixtures/state_tests
             mkdir -p fixtures/eof_tests
 
-            while IFS= read -r line; do
-              file=$(echo "$line" | cut -c 3-)
+            # Use a while loop with a here-string to avoid subshell issues
+            while IFS= read -r file; do
+             echo "Fill: $file"
               fill "$file" --until=Cancun --evm-bin evmone-t8n || true >> filloutput.log 2>&1
               (fill "$file" --fork=CancunEIP7692 --evm-bin evmone-t8n -k eof_test || true) > >(tee -a filloutput.log filloutputEOF.log) 2>&1
             done <<< "$files"
@@ -220,17 +233,15 @@ jobs:
 
             filesState=$(find fixtures/state_tests -type f -name "*.json")
             filesEOF=$(find fixtures/eof_tests -type f -name "*.json")
-            if [ -z "$filesState" ] && [ -z "$filesEOF" ]; then
-              echo "Error: No filled JSON fixtures found in fixtures from before the PR."
-               exit 1
-            fi
 
             BASE_TEST_PATH=${{ github.workspace }}/evmtest_coverage/coverage/BASE_TESTS
             mkdir -p $BASE_TEST_PATH
             find fixtures/state_tests -type f -name "*.json" -exec cp {} $BASE_TEST_PATH \;
             find fixtures/eof_tests -type f -name "*.json" -exec cp {} $BASE_TEST_PATH \;
             for file in $BASE_TEST_PATH/*.json; do
-              mv "$file" "${file%.json}_$PREV_COMMIT.json"
+                if [ -e "$file" ]; then
+                    mv "$file" "${file%.json}_$PREV_COMMIT.json"
+                fi
             done
 
 
